(in-package #:binstruct)

(declaim (ftype (function (single-float (mod 32) (mod 32)) (values (unsigned-byte 32))) single-float->ieee754-float-bits))
(defun single-float->ieee754-float-bits (float e f)
  (cond
    ((float-features:float-nan-p float)
     (logior (ash (ldb (byte 1 31) (float-features:single-float-bits float)) (+ e f))
             (ash (1- (ash 1 e)) f)
             1))
    ((float-features:float-infinity-p float)
     (logior (ash (ldb (byte 1 31) (float-features:single-float-bits float)) (+ e f))
             (ash (1- (ash 1 e)) f)))
    (t
     (multiple-value-bind (mantissa exp sign)
         (integer-decode-float float)
       (let* ((bias (1- (ash 1 (1- e))))
              (sign-bit (if (minusp sign) 1 0)))
         (if (zerop mantissa)
             (ash sign-bit (+ e f))
             (let ((ieee-exp (+ exp (integer-length mantissa) -1 bias)))
               (if (<= ieee-exp 0)
                   (let ((fraction (ash mantissa (- 1 bias f exp))))
                     (logior (ash sign-bit (+ e f))
                             (ldb (byte f 0) (if (plusp fraction) fraction 0))))
                   (let ((fraction (ldb (byte f 0) (ash mantissa (- f (1- (integer-length mantissa)))))))
                     (logior (ash sign-bit (+ e f))
                             (ash ieee-exp f)
                             fraction))))))))))

(declaim (ftype (function (double-float (mod 64) (mod 64)) (values (unsigned-byte 64))) double-float->ieee754-float-bits))
(defun double-float->ieee754-float-bits (float e f)
  (cond
    ((float-features:float-nan-p float)
     (logior (ash (ldb (byte 1 63) (float-features:double-float-bits float)) (+ e f))
             (ash (1- (ash 1 e)) f)
             1))
    ((float-features:float-infinity-p float)
     (logior (ash (ldb (byte 1 63) (float-features:double-float-bits float)) (+ e f))
             (ash (1- (ash 1 e)) f)))
    (t
     (multiple-value-bind (mantissa exp sign)
         (integer-decode-float float)
       (let* ((bias (1- (ash 1 (1- e))))
              (sign-bit (if (minusp sign) 1 0)))
         (if (zerop mantissa)
             (ash sign-bit (+ e f))
             (let ((ieee-exp (+ exp (integer-length mantissa) -1 bias)))
               (if (<= ieee-exp 0)
                   (let ((fraction (ash mantissa (- 1 bias f exp))))
                     (logior (ash sign-bit (+ e f))
                             (ldb (byte f 0) (if (plusp fraction) fraction 0))))
                   (let ((fraction (ldb (byte f 0) (ash mantissa (- f (1- (integer-length mantissa)))))))
                     (logior (ash sign-bit (+ e f))
                             (ash ieee-exp f)
                             fraction))))))))))

(defun float->ieee754-float-bits (float e f)
  (cond
    ((and (= e 8) (= f 23)) (float-features:single-float-bits float))
    ((and (= e 11) (= f 52)) (float-features:double-float-bits float))
    ((<= (+ 1 e f) 32) (single-float->ieee754-float-bits float e f))
    (t (double-float->ieee754-float-bits float e f))))

(defmethod expand-writer-type-expr ((name (eql 'ieee754-float)) &rest args)
  (destructuring-bind (e f) args
    (let ((*value* `(float->ieee754-float-bits ,*value* ,e ,f)))
      (expand-writer-type `(unsigned-byte ,(+ 1 e f))))))

(defmethod expand-writer-type-expr ((name (eql 'single-float)) &rest args)
  (declare (ignore args))
  (expand-writer-type '(ieee754-float 8 23)))

(defmethod expand-writer-type-expr ((name (eql 'double-float)) &rest args)
  (declare (ignore args))
  (expand-writer-type '(ieee754-float 11 52)))
